name: Attri_VAE
target_size: &id001 !!python/tuple
- 128
- 128
win_size: !!python/tuple
- 128
- 128
- 128
dbatch_size: 128
checkpoint_path: &id003 ./weights/
binary_label: true
attributes_idx: &id002 !!python/tuple
- LVEDV
- RVEDV
- MYOEDV
- LVESV
- RVESV
- MYOESV
rescale: 1
experiment:
  name: interp_rep
  task: train
  weights: null
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params: null
model:
  module_name: model_zoo.beta_vae_higgings
  class_name: BetaVAE_H
  params:
    z_dim: 128
    nc: 2
    additional_layer: true
    sigmoid: true
trainer:
  module_name: projects.interp_rep.VAETrainer
  class_name: PTrainer
  params:
    nc: 2
    input_size: *id001
    checkpoint_path: *id003
    nr_epochs: 1000
    patience: 50
    fctr: 0.0005
    loss_type: mse
    annealing: 1
    loss:
      module_name: projects.interp_rep.losses_VAE
      class_name: VAE_loss
      params:
        beta: 2
        gamma: 30
        factor: 10
    optimizer_params:
      lr: 5.0e-05
  data_loader:
    module_name: data.cardiac_loader_2D
    class_name: CardiacLoader
    params:
      args:
        patch_path: /lustre/groups/shared/ukbb-87065/dataset/cardiac_mri_nifti/preprocessing/dataset/healthy_5k/healthy_all_moment.h5
        attributes_path: /lustre/groups/shared/ukbb-87065/dataset/cardiac_mri_nifti/preprocessing/dataset/healthy_5k/
        attributes_idx: *id002
        win_size: *id001
        rescale: 1
        binary_label: true
        moment: all
        batch_size: 128
downstream_tasks:
  UKB:
    module_name: projects.interp_rep.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *id003
    data_loader:
      module_name: data.cardiac_loader_2D
      class_name: CardiacLoader
      params:
        args:
          patch_path: /lustre/groups/shared/ukbb-87065/dataset/cardiac_mri_nifti/preprocessing/dataset/healthy_5k/healthy_all_moment.h5
          attributes_path: /lustre/groups/shared/ukbb-87065/dataset/cardiac_mri_nifti/preprocessing/dataset/healthy_5k/
          attributes_idx: *id002
          win_size: *id001
          rescale: 1
          binary_label: true
          moment: all
          batch_size: 128
